### ISSUE TITLE
Geolocation.watchPosition().filter does not compile with ionic 2.2.0 and ionic-native 2.4.1

### ISSUE THREAD

**Issue by paoesco** [driftyco/ionic-native#1262]
Hello,

After updating Ionic and Ionic Native, it seems that part of my code is not compiling anymore.

```
var subscription = Geolocation.watchPosition()
                              .filter((p) => p.coords !== undefined) // error HERE
                              .subscribe(position => {
  console.log(position.coords.longitude + ' ' + position.coords.latitude);
});

// To stop notifications
subscription.unsubscribe();
```

The above code is from the documentation that can be found here : https://ionicframework.com/docs/v2/native/geolocation/

The error is :
```
Property 'filter' does not exist on type 'Observable<Geoposition>'.
```

My dependencies are :
```
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/cloud-angular": "0.11.0",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
```

One thing I have spotted is that when doing a `npm install` I have this :
```
├─┬ ionic-native@2.4.1 
│ └── rxjs@5.0.0-beta.12 
├── ionicons@3.0.0 
├─┬ rxjs@5.0.1 
│ └── symbol-observable@1.0.4 
```
It seems that ionic-native is still using rxjs 5.0.0-beta.12 and ionic 2.2.0 (and even 2.3.0 is using rxjs 5.0.1.

ionic info :

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002

Thanks

**Comment by ihadeed** [comment]
Update your `ionic-native` package to the latest version. 

```
npm I --save ionic-native@latest
```
