### ISSUE TITLE
Geolocation.watchPosition() example snippet doesn't compile

### ISSUE THREAD

**Issue by yzhan94** [driftyco/ionic-native#741]
Geolocation.watchPosition() example code doesn't compile; running `npm run build` throws the following errors:
```bash
[12:47:46]  Property 'code' does not exist on type 'Geoposition | PositionError'. 
[12:47:46]  Property 'coords' does not exist on type 'Geoposition | PositionError'. 
[12:47:46]  Property 'coords' does not exist on type 'Geoposition | PositionError'. 
[12:47:46]  ngc failed 
```
I'm using the latest ionic-app-scripts (v 0.0.36).
It can be reproduced using the snippet given in the [docs](https://ionicframework.com/docs/v2/native/geolocation/)
```typescript
var subscription = Geolocation.watchPosition()
                              .filter((p) => p.code === undefined) //Filter Out Errors
                              .subscribe(position => {
  console.log(position.coords.longitude + ' ' + position.coords.latitude);
});
```

A working solution I tried is changing the return type of the watchPosition method from the Union Type `Observable<Geoposition | PositionError>` to the Intersection Type `Observable<Geoposition & PositionError>`.

According to the [official documentation](https://www.typescriptlang.org/docs/handbook/advanced-types.html), in a Union Type, you can only access members that are common to all types in the union; whereas an Intersection Type object will have all the members of all types.

**Comment by ihadeed** [comment]
thanks

**Comment by nalkon** [comment]
I'm having the same problem. How do I get the fix?

Tnx.

**Comment by dnmd** [comment]
While using the latest ionic-native `"ionic-native": "^2.2.16"`, the issue still remains, it's not possible to compile the example snippet. From the logs:

````javascript
__WEBPACK_IMPORTED_MODULE_0_ionic_native__.a.watchPosition(...).filter is not a function
````

So I still remove the filter to get it compiled.

**Comment by raae** [comment]
@dnmd i got the same with 2.2.16, but works with 2.2.15

**Comment by ihadeed** [comment]
@raae 2.2.16 is the same as 2.2.15 except it has a major fix that is not related to this plugin. You should be using `2.2.16` as `2.2.15` is broken.

**Comment by ihadeed** [comment]
@dnmd  are you importing `rxjs/add/operator/filter` ?

**Comment by raae** [comment]
Ok @ihadeed it now works with 2.2.16, it must have been something else then.

**Comment by badpenguin** [comment]
I'm getting this problem after upgrading ionic-angular from 2.1.0 to 2.2.0

https://forum.ionicframework.com/t/type-observable-geoposition-is-not-assignable-to-type-observable-geoposition-after-upgrading-to-2-2-0/82314

**Comment by ihadeed** [comment]
@badpenguin thanks, this is because of the Rxjs version. Will push a hotfix soon.
