### ISSUE TITLE
[ionic-native 3.2.4] TypeError: plugin.constructor.getPluginRef is not a function

### ISSUE THREAD

**Issue by RafaelKr** [driftyco/ionic-native#1265]
I wrote a ionic-native wrapper for the plugin [cordova-plugin-qrscanner](https://github.com/bitpay/cordova-plugin-qrscanner), but when I run my application and call any method of QRScanner (in this case `QRScanner.prepare()`), it throws with this error:
```
Error: Uncaught (in promise): TypeError: plugin.constructor.getPluginRef is not a function
TypeError: plugin.constructor.getPluginRef is not a function
    at checkAvailability (main.js:81923)
    at callCordovaPlugin (main.js:82018)
    at main.js:82031
    at main.js:55921
    at new t (polyfills.js:3)
    at tryNativePromise (main.js:55920)
    at getPromise (main.js:55928)
    at wrapPromise (main.js:82030)
    at Function.<anonymous> (main.js:82142)
    at Function.value [as prepare] (main.js:115277)
    at main.js:115438
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (main.js:35928)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at v (polyfills.js:3)
    at s (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:35919)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
```

Steps to reproduce:
Download [attachments.zip](https://github.com/driftyco/ionic-native/files/872350/attachments.zip)
```
ionic start App -a "Test" blank --v2
cd App
npm i --save @ionic-native/core@3.2.4 # latest at time of writing
```
now merge the folder `App` from the attached zip with the directory `App` created by ionic.
This adds the directory `node_modules/@ionic-native/qr-scanner` (my ionic-native wrapper)
and overwrites the files `app.component.ts` and `app.module.ts` to add the plugin and call method `QRScanner.prepare()`.
```
ionic plugin add cordova-plugin-qrscanner --save
ionic platform add android
ionic run android --device
```
Now the attached stack trace should appear in the remote console.

I found the following workaround:
Replace the lines 11-15 (else-statement) in `node_modules/@ionic-native/core/plugin.js` with the following else-statement
```
else {
    plugin.constructor = plugin.constructor || {}; // maybe this line isn't even needed

    plugin.constructor.getPluginRef = plugin.constructor.getPluginRef || plugin.getPluginRef;
    plugin.constructor.getPluginName = plugin.constructor.getPluginName || plugin.getPluginName;
    plugin.constructor.getPluginInstallName = plugin.constructor.getPluginInstallName || plugin.getPluginInstallName;

    pluginRef = plugin.constructor.getPluginRef();
    pluginName = plugin.constructor.getPluginName();
    pluginPackage = plugin.constructor.getPluginInstallName();
}
```
now run `ionic run android --device` again and it should be working.
To see the camera view, you have to delete everything from `src/pages/home/home.html` and add this to your `app.scss`:
```
ion-app {
  background-color: transparent !important;
}
```

I don't know, if I made a mistake in my ionic-native-wrapper (also attached in the zip in `ionic-native-github-repo`) or if the plugin exposes somehow else than other plugins. Maybe you guys know.

Thanks for digging in!

**Comment by oborudko** [comment]
I had same error after switching to ionic-native3 when using .find on Contacts plugin,

```
cordova.js:314 Uncaught TypeError: plugin.constructor.getPluginRef is not a function
checkAvailability	@	plugin.js:12
Contact	@	index.js:17
processContact	@	index.js:267
(anonymous function)	@	index.js:234
win	@	contacts.js:58
callbackFromNative	@	cordova.js:293
(anonymous function)	@	VM2020:1
```
extract from packages.json
```
    "@ionic-native/contacts": "^3.2.4",
    "@ionic-native/core": "^3.2.4",
    "ionic-angular": "^2.3.0",
```

example code usage
```
                let options = new ContactFindOptions(attendee.email, false);
                this.contacts.find(['emails'], options).then(results => {
                    this.addContact(results.length ? results.shift() : this.contacts.create(), attendee);
                });
```

**Comment by ihadeed** [comment]
Fixed in `3.3.0`.

**Comment by oborudko** [comment]
Still getting the error, after update to 3.3.0,
```
cordova.js:314 
Uncaught TypeError: plugin.constructor.getPluginRef is not a function
checkAvailability @ plugin.js:12
Contact @ index.js:17
processContact @ index.js:267
(anonymous function) @ index.js:234
win @ contacts.js:58
callbackFromNative @ cordova.js:293
(anonymous function) @ VM518:1
```

```
    "@ionic-native/contacts": "^3.3.0",
    "@ionic-native/core": "^3.3.0",
```

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by RafaelKr** [comment]
Same for me with `"@ionic-native/core": "^3.4.0"`.
@oborudko Is my workaround working for you?

**Comment by ihadeed** [comment]
@RafaelKr  Update `@ionic-native/contacts` to latest version as well.

**Comment by RafaelKr** [comment]
I'm not using @ionic-native/contacts
I created this issue, because this happens with the plugin-wrapper I wrote for `cordova-plugin-qrscanner`.

**Comment by ihadeed** [comment]
@RafaelKr I can't tell what's wrong with it without seeing the source code.

Make sure your `@Plugin` decorator is there and has at least the following properties in it's config: `pluginName`, `plugin`, and `pluginRef`.

**Comment by RafaelKr** [comment]
The code is in attachements.zip which is attached in the first post of this issue. (https://github.com/driftyco/ionic-native/files/872350/attachments.zip)
I have all properties defined.

**Comment by ihadeed** [comment]
@RafaelKr 

- the class needs `@Injectable()` decorator (imported from `@angular/core`) 
- all methods should NOT be static

If you are planning to submit this wrapper as a PR, few more notes:
- the `QRScanner` class will be imported from `@ionic-native/qr-scanner`. This needs to be fixed in the `@usage` section of the docs
- the `@name` tag in the docs should read `QR Scanner`
- the `QRScannerStatus` interface should be above the class declaration

**Comment by RafaelKr** [comment]
Thank you! I will follow your guidance.
